const MenuItem = require('../models/MenuItem');
const multer = require('multer');
const { uploadImage, deleteImage } = require('../utils/cloudinary');

// Configure multer for file uploads
const storage = multer.diskStorage({
  filename: function (req, file, cb) {
    cb(null, Date.now() + '-' + file.originalname);
  }
});

const upload = multer({ storage });

// Default menu items for auto-generation
const defaultMenuItems = {
  morning: [
    { name: 'Idli', price: 30 },
    { name: 'Dosa', price: 40 },
    { name: 'Vada', price: 35 },
    { name: 'Poori', price: 40 },
    { name: 'Upma', price: 35 },
    { name: 'Pesarattu', price: 45 },
    { name: 'Tea', price: 15 },
    { name: 'Coffee', price: 20 }
  ],
  afternoon: [
    { name: 'Meals', price: 80 },
    { name: 'Biryani', price: 120 },
    { name: 'Fried Rice', price: 100 },
    { name: 'Chapati', price: 50 },
    { name: 'Pulao', price: 90 },
    { name: 'Curd Rice', price: 60 }
  ],
  evening: [
    { name: 'Samosa', price: 20 },
    { name: 'Bajji', price: 25 },
    { name: 'Tea', price: 15 },
    { name: 'Coffee', price: 20 },
    { name: 'Bonda', price: 25 },
    { name: 'Mirchi Bajji', price: 30 }
  ]
};

// @desc    Get all menu items or by category
// @route   GET /api/menu?category=morning
// @access  Public
const getMenuItems = async (req, res) => {
  try {
    const { category } = req.query;
    
    let query = {};
    if (category && ['morning', 'afternoon', 'evening'].includes(category.toLowerCase())) {
      query.category = category.toLowerCase();
    }

    const menuItems = await MenuItem.find(query).sort({ createdAt: -1 });

    res.json({
      success: true,
      count: menuItems.length,
      data: menuItems
    });
  } catch (error) {
    console.error('Get menu items error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching menu items'
    });
  }
};

// @desc    Create menu item
// @route   POST /api/menu
// @access  Private (Admin)
const createMenuItem = async (req, res) => {
  try {
    const { name, price, category, available } = req.body;

    // Validate required fields
    if (!name || !price || !category) {
      return res.status(400).json({
        success: false,
        message: 'Please provide name, price, and category'
      });
    }

    // Validate category
    if (!['morning', 'afternoon', 'evening'].includes(category.toLowerCase())) {
      return res.status(400).json({
        success: false,
        message: 'Category must be morning, afternoon, or evening'
      });
    }

    // Handle image upload if provided
    let imageUrl = '';
    if (req.file) {
      const uploadResult = await uploadImage(req.file.path, 'hotel-chandamama/menu');
      if (uploadResult.success) {
        imageUrl = uploadResult.url;
      }
    }

    const menuItem = await MenuItem.create({
      name,
      price: parseFloat(price),
      category: category.toLowerCase(),
      imageUrl,
      available: available !== undefined ? available : true,
      autoGenerated: false
    });

    res.status(201).json({
      success: true,
      message: 'Menu item created successfully',
      data: menuItem
    });
  } catch (error) {
    console.error('Create menu item error:', error);
    res.status(500).json({
      success: false,
      message: 'Error creating menu item'
    });
  }
};

// @desc    Update menu item
// @route   PUT /api/menu/:id
// @access  Private (Admin)
const updateMenuItem = async (req, res) => {
  try {
    const { id } = req.params;
    const { name, price, category, available } = req.body;

    let menuItem = await MenuItem.findById(id);
    if (!menuItem) {
      return res.status(404).json({
        success: false,
        message: 'Menu item not found'
      });
    }

    // Update fields
    if (name) menuItem.name = name;
    if (price) menuItem.price = parseFloat(price);
    if (category && ['morning', 'afternoon', 'evening'].includes(category.toLowerCase())) {
      menuItem.category = category.toLowerCase();
    }
    if (available !== undefined) menuItem.available = available;

    // Handle image upload if provided
    if (req.file) {
      const uploadResult = await uploadImage(req.file.path, 'hotel-chandamama/menu');
      if (uploadResult.success) {
        menuItem.imageUrl = uploadResult.url;
      }
    }

    await menuItem.save();

    res.json({
      success: true,
      message: 'Menu item updated successfully',
      data: menuItem
    });
  } catch (error) {
    console.error('Update menu item error:', error);
    res.status(500).json({
      success: false,
      message: 'Error updating menu item'
    });
  }
};

// @desc    Delete menu item
// @route   DELETE /api/menu/:id
// @access  Private (Admin)
const deleteMenuItem = async (req, res) => {
  try {
    const { id } = req.params;

    const menuItem = await MenuItem.findById(id);
    if (!menuItem) {
      return res.status(404).json({
        success: false,
        message: 'Menu item not found'
      });
    }

    await MenuItem.findByIdAndDelete(id);

    res.json({
      success: true,
      message: 'Menu item deleted successfully'
    });
  } catch (error) {
    console.error('Delete menu item error:', error);
    res.status(500).json({
      success: false,
      message: 'Error deleting menu item'
    });
  }
};

// @desc    Auto-generate menu items
// @route   POST /api/menu/auto-generate
// @access  Private (Admin)
const autoGenerateMenu = async (req, res) => {
  try {
    const generatedItems = [];

    // Generate items for each category
    for (const [category, items] of Object.entries(defaultMenuItems)) {
      for (const item of items) {
        const menuItem = await MenuItem.create({
          name: item.name,
          price: item.price,
          category: category,
          available: true,
          autoGenerated: true,
          imageUrl: ''
        });
        generatedItems.push(menuItem);
      }
    }

    res.status(201).json({
      success: true,
      message: `Generated ${generatedItems.length} menu items successfully`,
      count: generatedItems.length,
      data: generatedItems
    });
  } catch (error) {
    console.error('Auto-generate menu error:', error);
    res.status(500).json({
      success: false,
      message: 'Error auto-generating menu items'
    });
  }
};

module.exports = {
  getMenuItems,
  createMenuItem,
  updateMenuItem,
  deleteMenuItem,
  autoGenerateMenu,
  upload
};
